Semester2GroepslessenASP/Controllers/UserController.cs
using BusnLogicGL;
using UTDAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Semester2GroepslessenASP.Models;

namespace Semester2GroepslessenASP.Controllers
{
    public class UserController : Controller
    {
        UserContainer uc = new UserContainer(new UserMSSQLDAL());

        /// <summary>
        /// Deze view wordt aangeroepen na het inloggen. De gegevens van de user worden opgehaald,
        /// van de user wordt een UserVM gemaakt en deze worden aan de view meegegeven.
        /// </summary>
        /// <returns>De Index view met de UserVM</returns>
        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                string id = HttpContext.Session.GetString("ID");
                if (id != null)
                {
                    User user = uc.FindByID(Convert.ToInt64(id));
                    UserVM vm = new UserVM(user);
                    return View(vm);
                }
                return RedirectToAction("Login", "Home");
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Haalt alle users op, maakt hier UserVMs van, voegt deze toe aan een lijst
        /// en stuurt dit door naar de view.
        /// </summary>
        /// <returns>De AllUsers view, waaran de users worden meegegeven</returns>
        public IActionResult AllUsers()
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    List<User> users = uc.GetAll();
                    List<UserVM> userVMs = new List<UserVM>();
                    userVMs.Clear();
                    foreach (User u in users)
                    {
                        userVMs.Add(new UserVM(u.FirstName, u.LastName, u.AddressLine1, u.AddressLine2, u.DateOfBirth, u.Email, u.Password, u.PhoneNumber, u.ID, u.IsAdmin));
                    }
                    return View(userVMs);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Deze methode wordt aangeroepen wanneer de user een nieuwe user wil aanmaken
        /// </summary>
        /// <returns>De CreateUser view</returns>
        [HttpGet]
        public IActionResult CreateUser()
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Maakt een nieuwe user aan
        /// </summary>
        /// <param name="um">De details van de user</param>
        /// <returns>De geüpdate AllUsers pagina met de nieuwe user toegevoegd</returns>
        [HttpPost]
        public IActionResult CreateUser(UserVM um)
        {
            try
            {
                User u = new User(um.FirstName, um.LastName, um.AddressLine1, um.AddressLine2, um.DateOfBirth, um.Email, um.Password, um.PhoneNumber, um.ID, um.IsAdmin);
                uc.Create(u);
                return RedirectToAction("AllUsers");
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Haalt de gegevens op van de user die bij het ID hoort, maakt van de user een
        /// UserVM en geeft deze mee aan de view
        /// </summary>
        /// <param name="id">Het ID van de user</param>
        /// <returns>De UpdaetUser view met de UserVM</returns>
        [HttpGet]
        public IActionResult UpdateUser(int id)
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    User u = uc.FindByID(id);
                    UserVM vm = new UserVM(u.FirstName, u.LastName, u.AddressLine1, u.AddressLine2, u.DateOfBirth, u.Email, u.Password, u.PhoneNumber, u.ID, u.IsAdmin);
                    return View(vm);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Update de user
        /// </summary>
        /// <param name="vm">De meegegeven user</param>
        /// <returns>de AllUsers view</returns>
        [HttpPost]
        public IActionResult UpdateUser(UserVM vm)
        {
            try
            {
                User u = new User(vm.FirstName, vm.LastName, vm.AddressLine1, vm.AddressLine2, vm.DateOfBirth, vm.Email, vm.Password, vm.PhoneNumber, vm.ID, vm.IsAdmin);
                uc.Update(u);
                return RedirectToAction("AllUsers");
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Haalt de gegevens van de user op die bij het meegegeven ID hoort, maakt hier een
        /// UserVM van en geeft deze mee aan de view
        /// </summary>
        /// <param name="id">Het ID van de user</param>
        /// <returns>De DeleteUser view met de UserVM</returns>
        [HttpGet]
        public IActionResult DeleteUser(int id)
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    User u = uc.FindByID(id);
                    UserVM vm = new UserVM(u);
                    return PartialView(vm);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Delete de user
        /// </summary>
        /// <param name="vm">De meegegeven user</param>
        /// <returns>De geüpdate AllUsers view met de user verwijderd</returns>
        [HttpPost]
        public IActionResult DeleteUser(UserVM vm)
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    User u = new(vm.FirstName, vm.LastName, vm.AddressLine1, vm.AddressLine2, vm.DateOfBirth, vm.Email, vm.Password, vm.PhoneNumber, vm.ID, vm.IsAdmin);
                    uc.Delete(u);
                    return RedirectToAction("AllUsers");
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }
    }
}

Semester2GroepslessenASP/Controllers/WorkoutController.cs
using BusnLogicGL;
using UTDAL;
using Microsoft.AspNetCore.Mvc;
using Semester2GroepslessenASP.Models;

namespace Semester2GroepslessenASP.Controllers
{
    public class WorkoutController : Controller
    {
        WorkoutContainer wc = new WorkoutContainer(new WorkoutMSSQLDAL());

        /// <summary>
        /// Haalt alle workouts op, maakt hier WorkoutVMs van, voegt deze toe aan een lijst
        /// en stuurt dit door naar de view.
        /// </summary>
        /// <returns>De index view, waaran de workouts worden meegegeven</returns>
        public IActionResult Index()
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    List<Workout> workouts = wc.GetAll();
                    List<WorkoutVM> vms = new List<WorkoutVM>();
                    foreach (Workout w in workouts)
                    {
                        vms.Add(new WorkoutVM(w));
                    }
                    return View(vms);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Deze methode wordt aangeroepen wanneer de user een nieuwe workout aan wil maken
        /// </summary>
        /// <returns>De CreateWorkout view</returns>
        public IActionResult CreateWorkout()
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Maakt een nieuwe workout aan
        /// </summary>
        /// <param name="vm">De details van de workout</param>
        /// <returns>De geüpdate index pagina met de nieuwe workout toegevoegd</returns>
        [HttpPost]
        public IActionResult CreateWorkout(WorkoutVM vm)
        {
            try
            {
                Workout w = new Workout(vm.Name, vm.Description, vm.ID, vm.URL);
                wc.Create(w);
                return RedirectToAction("Index");
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Haalt de gegevens op van de workout die bij het ID hoort, maakt van de workout een
        /// WorkoutVM en geeft deze mee aan de view
        /// </summary>
        /// <param name="id">Het ID van de workout</param>
        /// <returns>De UpdateWorkout view met de WorkoutVM</returns>
        public IActionResult UpdateWorkout(int id)
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    Workout w = wc.FindByID(id);
                    WorkoutVM vm = new WorkoutVM(w);
                    return View(vm);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Update de workout
        /// </summary>
        /// <param name="vm">De meegegeven workout</param>
        /// <returns>de Index view</returns>
        [HttpPost]
        public IActionResult UpdateWorkout(WorkoutVM vm)
        {
            try
            {
                Workout w = new Workout(vm.Name, vm.Description, vm.ID, vm.URL);
                wc.Update(w);
                return RedirectToAction("Index");
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Haalt de gegevens van de workout op die bij het meegegeven ID hoort, maakt hier een
        /// WorkoutVM van en geeft deze mee aan de view
        /// </summary>
        /// <param name="id">Het ID van de workout</param>
        /// <returns>De DeleteWorkout view met de WorkoutVM</returns>
        [HttpGet]
        public IActionResult DeleteWorkout(int id)
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    Workout w = wc.FindByID(id);
                    WorkoutVM vm = new WorkoutVM(w);
                    return PartialView(vm);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Delete de workout
        /// </summary>
        /// <param name="vm">De meegegeven workout</param>
        /// <returns>De geüpdate index view met de workout verwijderd</returns>
        [HttpPost]
        public IActionResult DeleteWorkout(WorkoutVM vm)
        {
            try
            {
                Workout w = new(vm.Name, vm.Description, vm.ID, vm.URL);
                wc.Delete(w);
                return RedirectToAction("Index");
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }
    }
}

Semester2GroepslessenASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Anytime Fitness</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Semester2GroepslessenASP.styles.css" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Anytime Fitness</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (Context.Session.GetString("ID") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                        }
                        @if (Context.Session.GetString("ID") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="GroupClass" asp-action="Index">Group Classes</a>
                            </li>
                        }
                        @if (Context.Session.GetString("IsAdmin") == "True")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="GroupClass" asp-action="ClassAttendance">Class Attendance</a>
                            </li>
                        }
                        @if (Context.Session.GetString("IsAdmin") == "True")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AllUsers">Users</a>
                            </li>
                        }
                        @if (Context.Session.GetString("IsAdmin") == "True")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
                            </li>
                        }
                        @if (Context.Session.GetString("IsAdmin") == "True")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Workout" asp-action="Index">Workouts</a>
                            </li>
                        }
                        @if (Context.Session.GetString("ID") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Log in</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Log out</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Anytime Fitness
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>