Semester2GroepslessenASP/Controllers/GroupClassController.cs
using BusnLogicGL;
using UTDAL;
using Microsoft.AspNetCore.Mvc;
using Semester2GroepslessenASP.Models;

namespace Semester2GroepslessenASP.Controllers
{
    public class GroupClassController : Controller
    {
        GroupClassContainer gc = new GroupClassContainer(new GroupClassMSSQLDAL());
        UserContainer uc = new UserContainer(new UserMSSQLDAL());
        InstructorContainer ic = new InstructorContainer(new InstructorMSSQLDAL());
        WorkoutContainer wc = new WorkoutContainer(new WorkoutMSSQLDAL());
        AttendanceContainer ac = new AttendanceContainer(new AttendanceMSSQLDAL());

        /// <summary>
        /// Haalt alle groupclasses op, maakt hier GroupClassVMs van, voegt deze toe aan een lijst
        /// en stuurt dit door naar de view.
        /// </summary>
        /// <returns>De index view, waaran de groupclasses worden meegegeven</returns>
        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                int userID = Convert.ToInt32(HttpContext.Session.GetString("ID"));
                List<GroupClassVM> vms = new();
                List<GroupClass> classes = gc.GetAll();
                foreach (GroupClass g in classes)
                {
                    bool IsSignedUp = ac.IsAttending(userID, g.ID);
                    vms.Add(new GroupClassVM(g, IsSignedUp));
                }
                return View(vms);
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Haalt de gegevens op voor de groupclass waarvan het ID is meegegeven aan de view en
        /// maakt hier een GroupClassVM van
        /// </summary>
        /// <param name="iD">Het ID van de groupclass</param>
        /// <returns>De SignUp view en de groupclass</returns>
        [HttpGet]
        public IActionResult SignUp(int iD)
        {
            try
            {
                GroupClass g = gc.FindByID(iD);
                GroupClassVM vm = new GroupClassVM(g);
                return PartialView(vm);
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Deze methode wordt aangeroepen wanneer een lid zich aanmeld voor een groepsles.
        /// Je moet ingelogd zijn om deze methode te kunnen aanroepen
        /// </summary>
        /// <param name="gm">Groepsles waarbij die zich probeert aan te melden</param>
        /// <returns>De tekst "SignedUp" bij succes, anders melding dat er ingelogd moet worden</returns>
        [HttpPost]
        public IActionResult SignUp(GroupClassVM gm)
        {
            try
            {
                long userID = Convert.ToInt64(HttpContext.Session.GetString("ID"));
                if (userID != 0)
                {
                    ac.SignUp(userID, Convert.ToInt32(gm.ID));
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("You're not logged in");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Alle instructors en workouts worden hier meegegeven aan de view
        /// </summary>
        /// <returns>De CreateGC view met de InstructorVMs en WorkoutVMs</returns>
        public IActionResult CreateGC()
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    GroupClassInstructorsWorkoutsVM vms = new();
                    List<Instructor> instructors = ic.GetAll();
                    List<Workout> workouts = wc.GetAll();
                    foreach (var instructor in instructors)
                    {
                        vms.Instructors.Add(new InstructorVM(instructor));
                    }
                    foreach (var workout in workouts)
                    {
                        vms.Workouts.Add(new WorkoutVM(workout));
                    }
                    return View(vms);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Maakt een nieuwe groupclass aan
        /// </summary>
        /// <param name="gm">De details van de groupclass</param>
        /// <returns>De geüpdate index pagina met de nieuwe groupclass toegevoegd</returns>
        [HttpPost]
        public IActionResult CreateGC(GroupClassInstructorsWorkoutsVM gm)
        {
            try
            {
                GroupClass g = new GroupClass(gm.GroupClass.Name, gm.GroupClass.ID, gm.GroupClass.Duration, gm.GroupClass.Date,
                new Instructor(gm.GroupClass.Instructor.Name, gm.GroupClass.Instructor.ID, gm.GroupClass.Instructor.Specialty), new Workout(gm.GroupClass.Workout.Name, gm.GroupClass.Workout.Description, gm.GroupClass.Workout.ID, gm.GroupClass.Workout.URL));
                gc.Create(g);
                return RedirectToAction("Index");
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Alle instructors en workouts worden hier opgehaald en omgezet. De info van de groupclass
        /// die bij het ID hoort wordt opgehaald, van de groupclass wordt een GroupclassVM gemaakt en
        /// een lijst met instructors, workouts en de groupclass wordt meegegeven aan de view.
        /// </summary>
        /// <param name="iD">Het ID van de groupclass</param>
        /// <returns>De UpdateGC view met de instructorVMs, WorkoutVMs en GroupClassVM</returns>
        [HttpGet]
        public IActionResult UpdateGC(int iD)
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {
                    GroupClassInstructorsWorkoutsVM vms = new();
                    List<Instructor> instructors = ic.GetAll();
                    List<Workout> workouts = wc.GetAll();
                    foreach (var instructor in instructors)
                    {
                        vms.Instructors.Add(new InstructorVM(instructor));
                    }
                    foreach (var workout in workouts)
                    {
                        vms.Workouts.Add(new WorkoutVM(workout));
                    }
                    GroupClass g = gc.FindByID(iD);
                    vms.GroupClass = new GroupClassVM(g);
                    return View(vms);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Updatet de groupclass
        /// </summary>
        /// <param name="gm">De meegegeven GroupclassVM</param>
        /// <returns>De Index view</returns>
        [HttpPost]
        public IActionResult UpdateGC(GroupClassInstructorsWorkoutsVM gm)
        {
            try
            {
                GroupClass g = new GroupClass(gm.GroupClass.Name, gm.GroupClass.ID, gm.GroupClass.Duration, gm.GroupClass.Date, new Instructor(gm.GroupClass.Instructor.Name, gm.GroupClass.Instructor.ID, gm.GroupClass.Instructor.Specialty), new Workout(gm.GroupClass.Workout.Name, gm.GroupClass.Workout.Description, gm.GroupClass.Workout.ID, gm.GroupClass.Workout.URL));
                gc.Update(g);
                return RedirectToAction("Index");
            }
            catch (TemporaryException ex)
            {
                ViewBag.Message = ex.Message;
                return View("SqlError");
            }
            catch (PermanentException ex)
            {
                ViewBag.Message = ex.Message;
                return View("PermanentError");
            }
        }

        /// <summary>
        /// Haalt alle groupclasses op, maakt hier GroupClassVMs van, voegt deze toe aan een lijst
        /// en geeft deze mee aan de view.
        /// </summary>
        /// <returns>De ClassAttendance view met de GroupClassVMs</returns>
        [HttpGet]
        public IActionResult ClassAttendance()
        {
            try
            {
                if (HttpContext.Session.GetString("IsAdmin") == "True")
                {

Semester2GroepslessenASP/Views/GroupClass/Cancel.cshtml
@model GroupClassVM
@{
    ViewData["Title"] = "Cancel";
}

<div class="modal fade" id="SignUp" tabindex="-1" aria-labelledby="cancelLabel" aria-hidden="true">
    <div class=" modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cancelLabel" style="color:#0d6efd">Cancel</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action=Cancel>
                    <p>Cancel your enrolment here</p>
                    <b>@Html.Label("Class:")</b> @Model.Name
                    <br />
                    <br />
                    <b>@Html.Label("Instructor:")</b> @Model.Instructor.Name
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Back</button>
                <button type="button" class="btn btn-danger" data-save="modal" data-url="@Url.Action("Cancel","GroupClass")">Cancel</button>
            </div>
        </div>
    </div>
</div>

Semester2GroepslessenASP/Views/GroupClass/CheckAttendance.cshtml
@model List<UserVM>
@{
    ViewData["Title"] = "CheckAttendance";
}

<h1>Check Attendance</h1>

<div class="row">
    <div class="col-9">
        <h2 class="text-primary">Attending Users</h2>
    </div>
</div>
<div class="p-4 border rounded">
    <table id="tblData" class="table table-striped table-bordered">
        <caption>Signed up users</caption>
        <thead>
            <tr class="table-secondary">
                <th>First Name</th>
                <th>Last Name</th>
                <th>User ID</th>
            </tr>
        </thead>
        @if (Model.Count > 0)
        {
            @foreach (UserVM um in Model)
            {
                <tr>
                    <td>@um.FirstName</td>
                    <td>@um.LastName</td>
                    <td>@um.ID</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>No records</td>
                <td>No records</td>
                <td>No records</td>
            </tr>
        }
    </table>
</div>

Semester2GroepslessenASP/Views/GroupClass/ClassAttendance.cshtml
@model List<GroupClassVM>
@{
    ViewData["Title"] = "ClassAttendance";
}

<h1>Choose a class to check attendance</h1>

<div class="row">
    <div class="col-9">
        <h2 class="text-primary">Classes</h2>
    </div>
</div>
<div class="p-4 border rounded">
    <table id="tblData" class="table table-striped table-bordered">
        <caption>Available classes</caption>
        <thead>
            <tr class="table-secondary">
                <th>Class</th>
                <th>Duration</th>
                <th>Date</th>
                <th>Instructor</th>
                <th>Attendance</th>
            </tr>
        </thead>
        @foreach (GroupClassVM vm in Model)
        {
            <tr>
                <td>@vm.Name</td>
                <td>@vm.Duration</td>
                <td>@vm.Date</td>
                <td>@vm.Instructor.Name</td>
                <td>
                    <a asp-action=CheckAttendance asp-route-id=@vm.ID>
                        <input type="submit" value="Check Attendance" class="btn btn-success" />
                    </a>
                </td>
            </tr>
        }
    </table>
</div>

Semester2GroepslessenASP/Views/GroupClass/CreateGC.cshtml
@model GroupClassInstructorsWorkoutsVM
@{
    ViewData["Title"] = "CreateGC";
}

<h1>Create Group Class</h1>
<br />
Enter the information down below to create a new group class
<br />
<br />
<form asp-action=CreateGC asp-method="post">
    @Html.Label("Instructors: ")
    <select id="instructors" onclick="ChooseInstructor()">
        @foreach (InstructorVM instructor in Model.Instructors)
        {
            <option value=@instructor.ID>@instructor.Name</option>
        }
    </select>
    <br />
    <br />
    @Html.Label("Workouts: ")
    <select id="workouts" onclick="ChooseWorkout()">
        @foreach (WorkoutVM workout in Model.Workouts)
        {
            <option value=@workout.ID>@workout.Name</option>
        }
    </select>
    <br />
    <p><input type="hidden" id="textI" asp-for=@Model.GroupClass.Instructor.Name required maxlength="50" /></p>
    <p><input type="hidden" id="textW" asp-for=@Model.GroupClass.Workout.Name required maxlength="50" /></p>
    @Html.Label("Name: ")
    <input asp-for=@Model.GroupClass.Name required maxlength="50" />
    <br />
    <br />
    @Html.Label("Duration: ")
    <input asp-for=@Model.GroupClass.Duration type="number" required oninput="this.value=this.value.slice(0,10)" />
    <br />
    <br />
    @Html.Label("Date: ")
    <input asp-for=@Model.GroupClass.Date required type="datetime-local" min="1753-01-01 00:00" />
    <br />
    <br />
    <p><input type="hidden" asp-for=@Model.GroupClass.ID /></p>
    <p><input type="hidden" id="insID" asp-for=@Model.GroupClass.Instructor.ID required maxlength="50" /></p>
    <p><input type="hidden" id="workoutID" asp-for=@Model.GroupClass.Workout.ID required maxlength="50" /></p>
    <p><input type="hidden" asp-for=@Model.GroupClass.Instructor.Specialty /></p>
    <p><input asp-for=@Model.GroupClass.Workout.URL type="hidden" /></p>
    <p><input asp-for=@Model.GroupClass.Workout.Description type="hidden" /></p>
    <br />
    <br />
    <input type="submit" class="btn btn-primary" value="Create" />
</form>

Semester2GroepslessenASP/Views/GroupClass/Index.cshtml
@model List<GroupClassVM>
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Index";
}
<div id="PlaceHolderHere"></div>

<h1>All classes</h1>
<head>
</head>
<div class="row">
    <div class="col-9">
        <h2 class="text-primary">Classes</h2>
    </div>
    <div class="col-3 text-right">
        @if (Context.Session.GetString("IsAdmin") == "True")
        {
            <a asp-action=CreateGC>
                <input type="submit" class="btn btn-primary" value="Create New Class" />
            </a>
            <br />
            <br />
        }
        <input id="myInput" type="text" placeholder="Search">
    </div>
</div>
<br />
<div class="p-4 border rounded">
    <table id="tblData" class="table table-striped table-bordered">
        <caption>Available classes</caption>
        <thead>
            <tr class="table-secondary">
                <th>Workout Class Name</th>
                <th>Duration</th>
                <th>Time</th>
                <th>Instructor</th>
                <th>Workout</th>
                @if (Context.Session.GetString("IsAdmin") == "True")
                {
                    <th>Admintool</th>
                }
                else
                {
                    <th>Sign up</th>
                }
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (GroupClassVM vm in Model)
            {
                <tr>
                    <td>@vm.Name</td>
                    <td>@vm.Duration</td>
                    <td>@vm.Date</td>
                    <td>@vm.Instructor.Name</td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="ajax-modal" data-target="#WorkoutInfo" data-url="@Url.Action("WorkoutInfo", "GroupClass", new {id = vm.ID})">
                            @vm.Workout.Name
                        </button>
                    </td>
                    @if (Context.Session.GetString("IsAdmin") == "True")
                    {
                        <td>
                            <a asp-action=UpdateGC asp-route-id="@vm.ID">
                                <input type="submit" class="btn btn-success" value="Edit" />
                            </a>
                            <button type="button" class="btn btn-danger" data-toggle="ajax-modal" data-target="#DeleteGC" data-url="@Url.Action("DeleteGC", "GroupClass", new {id = vm.ID})">
                                Delete
                            </button>
                        </td>
                    }
                    else
                    {
                        <td>
                            @if (@vm.IsSignedUp == false)
                            {
                                <button type="button" class="btn btn-success" data-toggle="ajax-modal" data-target="#SignUp" data-url="@Url.Action("SignUp", "GroupClass", new {id = vm.ID})">
                                    Sign Up
                                </button>
                            }
                            else
                            {
                                <button type="button" class="btn btn-danger" data-toggle="ajax-modal" data-target="#Cancel" data-url="@Url.Action("Cancel", "GroupClass", new {id = vm.ID})">
                                    Cancel
                                </button>
                            }
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

Semester2GroepslessenASP/Views/GroupClass/SignUp.cshtml
@model GroupClassVM
@{
    ViewData["Title"] = "SignUp";
}

<div class="modal fade" id="SignUp" tabindex="-1" aria-labelledby="signUpLabel" aria-hidden="true">
    <div class=" modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="signUpLabel" style="color:#0d6efd">Sign Up</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action=SignUp>
                    <p>Confirm your enrolment here</p>
                    <b>@Html.Label("Class:")</b> @Model.Name
                    <br />
                    <br />
                    <b>@Html.Label("Instructor:")</b> @Model.Instructor.Name
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
                <button type="button" class="btn btn-success" data-save="modal" data-url="@Url.Action("SignUp","GroupClass")">Sign Up</button>
            </div>
        </div>
    </div>
</div>

Semester2GroepslessenASP/Views/GroupClass/UpdateGC.cshtml
@model GroupClassInstructorsWorkoutsVM
@{
    ViewData["Title"] = "UpdateGC";
}

<h1>Update Group Class</h1>
<br />
Enter the information down below to update the group class
<br />
<br />
<form asp-action=UpdateGC asp-method="post">
    @Html.Label("Instructors: ")
    <select id="instructors" onclick="ChooseInstructor()">
        @foreach (InstructorVM instructor in Model.Instructors)
        {
            <option value=@instructor.ID>@instructor.Name</option>
        }
    </select>
    <br />
    <br />
    @Html.Label("Workouts: ")
    <select id="workouts" onclick="ChooseWorkout()">
        @foreach (WorkoutVM workout in Model.Workouts)
        {
            <option value=@workout.ID>@workout.Name</option>
        }
    </select>
    <br />
    <p><input type="hidden" id="textI" asp-for=@Model.GroupClass.Instructor.Name required maxlength="50" /></p>
    <p><input type="hidden" id="textW" asp-for=@Model.GroupClass.Workout.Name required maxlength="50" /></p>
    @Html.Label("Name: ")
    <input asp-for=@Model.GroupClass.Name required maxlength="50" />
    <br />
    <br />
    @Html.Label("Duration: ")
    <input asp-for=@Model.GroupClass.Duration type="number" required oninput="this.value=this.value.slice(0,10)" />
    <br />
    <br />
    @Html.Label("Date: ")
    <input asp-for=@Model.GroupClass.Date required type="datetime-local" min="1753-01-01 00:00" />
    <br />
    <br />
    <p><input type="hidden" asp-for=@Model.GroupClass.ID /></p>
    <p><input type="hidden" id="insID" asp-for=@Model.GroupClass.Instructor.ID required maxlength="50" /></p>
    <p><input type="hidden" id="workoutID" asp-for=@Model.GroupClass.Workout.ID required maxlength="50" /></p>
    <p><input type="hidden" asp-for=@Model.GroupClass.Instructor.Specialty /></p>
    <p><input asp-for=@Model.GroupClass.Workout.URL type="hidden" /></p>
    <p><input asp-for=@Model.GroupClass.Workout.Description type="hidden" /></p>
    <br />
    <br />
    <input type="submit" class="btn btn-success" value="Edit" />
</form>